{{- if .Values.enhancedHA.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "atlantis.fullname" . }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "atlantis.selectorLabels" . | nindent 6 }}
  {{- if .Values.enhancedHA.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.enhancedHA.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.enhancedHA.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.enhancedHA.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
