{{- if and .Values.enhancedDeployment.enabled (eq .Values.enhancedDeployment.type "rollout") (eq .Values.enhancedDeployment.strategy "blueGreen") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlantis.fullname" . }}-preview
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.atlantis.service.type | default "ClusterIP" }}
  selector:
    {{- include "atlantis.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.atlantis.service.port | default 4141 }}
      targetPort: {{ .Values.atlantis.service.targetPort | default 4141 }}
      protocol: TCP
      name: http
{{- end }}
