apiVersion: v2
name: atlantis
description: Enhanced Atlantis Helm chart with Argo Rollouts, monitoring, and HA features
type: application
version: 0.1.6
appVersion: "latest"
icon: https://avatars.githubusercontent.com/u/32311288
keywords:
  - atlantis
  - terraform
  - automation
  - ci-cd
  - argo-rollouts
  - monitoring
maintainers:
  - name: k8sforge
home: https://github.com/k8sforge/atlantis-chart
sources:
  - https://github.com/runatlantis/atlantis
  - https://github.com/k8sforge/atlantis-chart
dependencies:
  - name: atlantis
    version: "5.24.1"
    repository: "https://runatlantis.github.io/helm-charts"
